question_data = [
    {"response_code": 0, "results": [{"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "The first computer bug was formed by faulty wires.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "FLAC stands for &quot;Free Lossless Audio Condenser&quot;&#039;",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "MacOS is based on Linux.", "correct_answer": "False",
                                      "incorrect_answers": ["True"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "The open source program Redis is a relational database server.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "AMD created the first consumer 64-bit processor.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                      "question": "&quot;HTML&quot; stands for Hypertext Markup Language.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
                                      "question": "The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                      "question": "Time on Computers is measured via the EPOX System.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "The last Windows operating system to be based on the Windows 9x kernel was Windows 98.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                      "question": "Linux was first created as an alternative to Windows XP.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "Android versions are named in alphabetical order.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                      "question": "The Python programming language gets its name from the British comedy group &quot;Monty Python.&quot;",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
                                      "question": "The T-Mobile Sidekick smartphone is a re-branded version of the Danger Hiptop.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]}]}
]
